import type { NextPage } from "next"
import Head from "next/head"
import Link from 'next/link'
import { trpc } from "../utils/trpc"

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>LostAndFound - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center">
        <h2 className="text-lg font-bold mb-3" >Home Page</h2>
        <div>Coming soon...</div>
      </main>
    </>
  )
}

export default Home
