import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import welcomeImg from '../../public/welcome.png'
import Link from 'next/link'
import { trpc } from "../utils/trpc"

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>LostAndFound - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center">
        <h2 className="text-xl text-green-900 font-bold mb-3" >Welcome to Lost & Found</h2>
        <div>
          <Image
            src={welcomeImg}
            alt='Welcome image'
          />
        </div>
      </main>
    </>
  )
}

export default Home
