import type { NextPage } from "next"
import { useSession } from 'next-auth/react'
import NextError from 'next/error'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { trpc } from '../../utils/trpc'
import { TrashIcon } from '@heroicons/react/solid'
import { PencilIcon } from '@heroicons/react/solid'
// import { QrcodeIcon } from '@heroicons/react/solid'
import { QrcodeIcon } from '@heroicons/react/outline'

const PostViewPage: NextPage = () => {
  const userId = useSession().data?.user?.id
  const router = useRouter()
  const id = router.query.id as string
  const utils = trpc.useContext()
  const postQuery = trpc.useQuery(['post.byId', { id }])
  const commentsQuery = trpc.useQuery(['comments.byPostId', { id }])
  const addComment = trpc.useMutation('comments.add', {
    async onSuccess() {
      // refetches comments after a comment is added
      await utils.invalidateQueries(['comments.byPostId', { id }])
    },
  })
  const deleteComment = trpc.useMutation('comments.delete', {
    async onSuccess() {
      // refetches comments after a comment is deleted
      await utils.invalidateQueries(['comments.byPostId', { id }])
    },
  })
  const deletePost = trpc.useMutation('post.delete', {
    async onSuccess() {
      // redirect to posts page
      router.push('/posts')
    },
  })

  if (postQuery.error) {
    return (
      <NextError
        title={postQuery.error.message}
        statusCode={postQuery.error.data?.httpStatus ?? 500}
      />
    )
  }

  if (postQuery.status !== 'success') {
    return <>Loading...</>
  }

  const { data } = postQuery

  return (
    <>
      <Head>
        <title>LostAndFound - {`${data.title}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h2 className="text-lg font-bold mb-2" >Item details</h2>
        <div className="flex flex-col justify-between w-full p-2 rounded-md shadow-lg bg-white">
          <div className="flex justify-between">
            <h3 className="text-slate-900 text-xl leading-tight font-medium mr-2">
              {data.title}
            </h3>
            {userId === data.userId && (
              <>
                <div className="flex-1">
                  <button
                    className=''
                    onClick={() => { }}
                  >
                    <PencilIcon className="h-6 w-6 text-slate-600 hover:text-red-500" />
                  </button>
                </div>
                <div className=''>
                  <button
                    className=''
                    onClick={() => deletePost.mutate({ id: data.id })}
                  >
                    <TrashIcon className="h-6 w-6 text-slate-600 hover:text-red-500" />
                  </button>
                </div>
              </>
            )}
          </div>


          <p className="text-xs italic">Added on {data.createdAt.toLocaleDateString()}</p>
          <p className="text-slate-700 text-base my-2 flex-1">
            {data.text}
          </p>
          <div>
            <button className='mr-2 flex items-center gap-1 mt-2 px-2 py-1.5 bg-slate-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-slate-700 hover:shadow-lg focus:bg-slate-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-slate-800 active:shadow-lg transition duration-150 ease-in-out'>
              <QrcodeIcon className="h-6 w-6" />
              QR Code
            </button>
          </div>
        </div>
      </div>

      <h2 className="text-lg font-bold mt-3" >Messages</h2>
      <ul>
        {commentsQuery.data?.map((comment) => (
          <li key={comment.id}>
            <div className={`flex ${userId == comment.userId ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className={`flex justify-between text-white my-2 p-2 min-w-full md:min-w-[60%] rounded-md shadow-lg ${userId == comment.userId ? 'bg-blue-500' : 'bg-green-500'}`}>
                <div>
                  <p className="font-bold">{comment.name}</p>
                  <p className='my-2'>{comment.text}</p>
                  <p className='text-xs italic text-gray-700'>{comment.createdAt.toLocaleString()}</p>
                </div>
                {userId === data.userId && (
                  <div>
                    <button
                      className=''
                      onClick={() => deleteComment.mutate({ id: comment.id })}
                    >
                      <TrashIcon className="h-6 w-6 text-white hover:text-red-500" />
                    </button>
                  </div>
                )}

              </div>
            </div>
          </li>
        ))}
      </ul>

      <div>
        <h2 className="text-lg font-bold my-3" >Send a message</h2>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            let nameSuffix: string
            userId ? nameSuffix = ' (Owner)' : nameSuffix = ' (Finder)'
            const $name: HTMLInputElement = (event as any).target.elements.name
            const $comment: HTMLInputElement = (event as any).target.elements.comment
            const input = {
              name: $name.value + nameSuffix,
              text: $comment.value,
              postId: id,
            }

            addComment.mutate(input)

            $name.value = ''
            $comment.value = ''
          }}
        >
          <div className='mb-2 flex flex-col'>
            <label className='font-semibold' htmlFor="name">Name (optional)</label>
            <input
              className="w-48 p-2 rounded-md"
              id="name"
              type="text"
              name="name"
              placeholder='Anonymous'
            />
          </div>
          <div className='mb-2 flex flex-col'>
            <label className='font-semibold' htmlFor="comment">Message</label>
            <textarea
              className="w-96 p-2 rounded-md"
              id="comment"
              name="comment"
              required
              maxLength={150}
              rows={3}
            >
            </textarea>
          </div>
          <input type="hidden" name="postId" value={id} />
          {/* <button type="submit">Send Message</button> */}
          <input
            className='inline-block my-2 px-2 py-1.5 bg-slate-600 text-white font-medium text-xs leading-tight rounded shadow-md hover:bg-slate-700 hover:shadow-lg focus:bg-slate-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-slate-800 active:shadow-lg transition duration-150 ease-in-out'
            type="submit"
          />
        </form>
      </div>
    </>
  )
}

export default PostViewPage
